In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('Telco-Customer-Churn.csv')
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
data = pd.read_csv('Telco-Customer-Churn.csv')
data = data.drop("customerID", axis=1)
data = data.drop("SeniorCitizen", axis=1)
data.head()

gender Partner Dependents  tenure PhoneService     MultipleLines  \
0  Female     Yes         No       1           No  No phone service   
1    Male      No         No      34          Yes                No   
2    Male      No         No       2          Yes                No   
3    Male      No         No      45           No  No phone service   
4  Female      No         No       2          Yes                No   

  InternetService OnlineSecurity OnlineBackup DeviceProtection TechSupport  \
0             DSL             No          Yes               No          No   
1             DSL            Yes           No              Yes          No   
2             DSL            Yes          Yes               No          No   
3             DSL            Yes           No              Yes         Yes   
4     Fiber optic             No           No               No          No   

  StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No              No  Month-to-month              Yes   
1          No              No        One year               No   
2          No              No  Month-to-month              Yes   
3          No              No        One year               No   
4          No              No  Month-to-month              Yes   

               PaymentMethod  MonthlyCharges TotalCharges Churn  
0           Electronic check           29.85        29.85    No  
1               Mailed check           56.95       1889.5    No  
2               Mailed check           53.85       108.15   Yes  
3  Bank transfer (automatic)           42.30      1840.75    No  
4           Electronic check           70.70       151.65   Yes

In [4]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd

data = pd.read_csv('Telco-Customer-Churn.csv')

le = LabelEncoder()
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

X = data.drop(columns=['Churn'])
y = data['Churn']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_classifier = SVC(kernel='linear', random_state=42)
svm_classifier.fit(X_train_scaled, y_train)

y_pred = svm_classifier.predict(X_test_scaled)

accuracy1 = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy1)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Accuracy: 0.8050165641268339
Confusion Matrix:
 [[1386  153]
 [ 259  315]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.90      0.87      1539
           1       0.67      0.55      0.60       574

    accuracy                           0.81      2113
   macro avg       0.76      0.72      0.74      2113
weighted avg       0.80      0.81      0.80      2113



In [5]:
from sklearn.tree import DecisionTreeClassifier

X = data.drop(columns=['Churn'])
y = data['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_test)

accuracy2 = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy2)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.7359204921911974
Confusion Matrix:
 [[1260  279]
 [ 279  295]]


In [6]:
from sklearn.ensemble import RandomForestClassifier

X = data.drop(columns=['Churn'])
y = data['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy3 = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy3)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Accuracy: 0.7988641741599621
Confusion Matrix:
 [[1401  138]
 [ 287  287]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.87      1539
           1       0.68      0.50      0.57       574

    accuracy                           0.80      2113
   macro avg       0.75      0.71      0.72      2113
weighted avg       0.79      0.80      0.79      2113



In [7]:
from sklearn.ensemble import AdaBoostClassifier

X = data.drop(columns=['Churn'])
y = data['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

adaboost_classifier = AdaBoostClassifier(n_estimators=50, random_state=42)
adaboost_classifier.fit(X_train, y_train)

y_pred = adaboost_classifier.predict(X_test)

accuracy4 = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy4)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Accuracy: 0.8002839564600095
Confusion Matrix:
 [[1394  145]
 [ 277  297]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.87      1539
           1       0.67      0.52      0.58       574

    accuracy                           0.80      2113
   macro avg       0.75      0.71      0.73      2113
weighted avg       0.79      0.80      0.79      2113



In [8]:
print("The accuracies are:")

print(f"SVM: {accuracy1}:")
print(f"Decison Tree: {accuracy2}")
print(f"Random Forest: {accuracy3}")
print(f"AdaBoost: {accuracy4}")

print(f"\nThe algorithm with best accuracy is SVM with an {accuracy1:.2f}.")

The accuracies are:
SVM: 0.8050165641268339:
Decison Tree: 0.7359204921911974
Random Forest: 0.7988641741599621
AdaBoost: 0.8002839564600095

The algorithm with best accuracy is SVM with an 0.81.


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV 
import warnings 

warnings.filterwarnings('ignore') 

df = pd.read_csv('Telco-Customer-Churn.csv') 

df.drop('customerID', inplace=True, axis=1) 

df['TotalCharges'] = df['TotalCharges'].apply(pd.to_numeric, errors='coerce') 

df.isnull().sum() 

df['TotalCharges'].fillna(df['TotalCharges'].mean(), inplace=True) 

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
object_columns = df.select_dtypes(include='object').columns 
df[object_columns] = df[object_columns].apply(lambda x: le.fit_transform(x)) 


x = df.iloc[:, :-1].values 
y = df.iloc[:, -1].values 


from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42) 

from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 
x_train = scaler.fit_transform(x_train) 
x_test = scaler.transform(x_test) 

from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier() 
knn.fit(x_train, y_train) 

knn_params = {'n_neighbors': np.arange(1, 50)} 

print("Grid Search for KNN:") 
grid_knn = GridSearchCV(knn, knn_params, scoring='accuracy', cv=9, n_jobs=-1) 
grid_knn.fit(x_train, y_train) 
print("Best parameters:", grid_knn.best_params_) 
print("Best score:", grid_knn.best_score_) 

print("\nRandomized Search for KNN:") 
rand_knn = RandomizedSearchCV(knn, knn_params, scoring='accuracy', cv=9, n_jobs=-1) 
rand_knn.fit(x_train, y_train) 
print("Best parameters:", rand_knn.best_params_) 
print("Best score:", rand_knn.best_score_) 

from sklearn.linear_model import LogisticRegression 
lr = LogisticRegression() 


lr_params = {'solver': ['newton-cg', 'lbfgs', 'sag'], 'C': np.logspace(-3, 2.45, 7), 'penalty': ['l1', 'l2']} 

print("\nGrid Search for Logistic Regression:") 
grid_lr = GridSearchCV(lr, lr_params, scoring='accuracy', cv=9, n_jobs=-1) 
grid_lr.fit(x_train, y_train) 
print("Best parameters:", grid_lr.best_params_) 
print("Best score:", grid_lr.best_score_) 

print("\nRandomized Search for Logistic Regression:") 
rand_lr = RandomizedSearchCV(lr, lr_params, scoring='accuracy', cv=9, n_jobs=-1) 
rand_lr.fit(x_train, y_train) 
print("Best parameters:", rand_lr.best_params_) 
print("Best score:", rand_lr.best_score_) 

from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB() 

gnb_params = {'var_smoothing': np.logspace(5, -7, 79)} 

print("\nGrid Search for Naive Bayes:") 
grid_gnb = GridSearchCV(gnb, gnb_params, scoring='accuracy', cv=9, n_jobs=-1) 
grid_gnb.fit(x_train, y_train) 
print("Best parameters:", grid_gnb.best_params_) 
print("Best score:", grid_gnb.best_score_) 

print("\nRandomized Search for Naive Bayes:") 
rand_gnb = RandomizedSearchCV(gnb, gnb_params, scoring='accuracy', cv=9, n_jobs=-1) 
rand_gnb.fit(x_train, y_train) 
print("Best parameters:", rand_gnb.best_params_) 
print("Best score:", rand_gnb.best_score_) 

from sklearn.tree import DecisionTreeClassifier 
dtc = DecisionTreeClassifier() 

dtc_params = {'criterion': ['gini', 'entropy'], 'max_depth': np.arange(1, 20), 'min_samples_split': np.arange(2, 10), 'max_features': np.arange(1, 7)} 

print("\nGrid Search for Decision Trees:") 
grid_dtc = GridSearchCV(dtc, dtc_params, scoring='accuracy', cv=9, n_jobs=-1) 
grid_dtc.fit(x_train, y_train) 
print("Best parameters:", grid_dtc.best_params_) 
print("Best score:", grid_dtc.best_score_) 

print("\nRandomized Search for Decision Trees:") 
rand_dtc = RandomizedSearchCV(dtc, dtc_params, scoring='accuracy', cv=9, n_jobs=-1) 
rand_dtc.fit(x_train, y_train) 
print("Best parameters:", rand_dtc.best_params_) 
print("Best score:", rand_dtc.best_score_) 

from sklearn.svm import SVC 
svc = SVC() 

svc_params = {'C': [0.1, 1, 10, 100], 'gamma': [0.1, 0.001, 0.01, 0.001], 'kernel': ['poly', 'sigmoid', 'rbf']} 

print("\nGrid Search for SVM:") 
grid_svc = GridSearchCV(svc, svc_params, scoring='accuracy', cv=9, n_jobs=-1) 
grid_svc.fit(x_train, y_train) 
print("Best parameters:", grid_svc.best_params_) 
print("Best score:", grid_svc.best_score_) 

print("\nRandomized Search for SVM:") 
rand_svc = RandomizedSearchCV(svc, svc_params, scoring='accuracy', cv=9, n_jobs=-1) 
rand_svc.fit(x_train, y_train) 
print("Best parameters:", rand_svc.best_params_) 
print("Best score:", rand_svc.best_score_) 

Grid Search for KNN:
Best parameters: {'n_neighbors': 44}
Best score: 0.7797130555073681

Randomized Search for KNN:
Best parameters: {'n_neighbors': 43}
Best score: 0.7770764666373096

Grid Search for Logistic Regression:
Best parameters: {'C': 0.06556418494179789, 'penalty': 'l2', 'solver': 'newton-cg'}
Best score: 0.7993916533595472

Randomized Search for Logistic Regression:
Best parameters: {'solver': 'sag', 'penalty': 'l2', 'C': 0.06556418494179789}
Best score: 0.7993916533595472

Grid Search for Naive Bayes:
Best parameters: {'var_smoothing': 2.424462017082326}
Best score: 0.7853958256418925

Randomized Search for Naive Bayes:
Best parameters: {'var_smoothing': 0.02424462017082326}
Best score: 0.7484832107892196

Grid Search for Decision Trees:
Best parameters: {'criterion': 'entropy', 'max_depth': 7, 'max_features': 5, 'min_samples_split': 9}
Best score: 0.7902590403157531

Randomized Search for Decision Trees:
Best parameters: {'min_samples_split': 7, 'max_features': 3, 'max_d